name: CI

on: [push, pull_request]

env:
  DOTNET_SDK_VERSION: '3.1.403'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
    - name: install dotnet sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Build and test
      shell: pwsh
      run: |
        $shellExt = if ($IsWindows) { "cmd" } else { "sh" }
        & ./build-and-test.$shellExt --configuration ${{ matrix.configuration }}

  nuget-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - run: .\build-and-test.cmd -c Release -notest
    - run: .\src\create-package.cmd
    - run: dotnet nuget push .\artifacts\packages\Release\IxMilia.Dxf.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
